"""
Generates diary_weeks.json — all 52 weeks, bilingual, with the freemium
'chapter' field so the app can gate weeks 17-52.

This reconstructs the diary content authored earlier in the project.
Week -> chapter mapping: chapter = ceil(week / 4), capped so weeks 45-52
belong to the integration/year-end arc (chapters 12).
"""
import json, math

# (week_number, theme_en, theme_id, principle_en, principle_id,
#  intent_en, intent_id, sunday_en, sunday_solo_en, sunday_id, sunday_solo_id)
WEEKS = [
 (1,"What I'm Actually Aiming At","Apa yang Sebenarnya Saya Tuju",
  "Most daily parenting friction is downstream of an unclear goal.",
  "Sebagian besar gesekan harian berakar pada tujuan yang belum jelas.",
  "What kind of adult do I most hope my child will grow into? Three qualities.",
  "Sosok dewasa seperti apa yang paling saya harapkan dari anak saya? Sebutkan tiga kualitas.",
  "What did we correct most this week — and was it shaping the qualities we said we wanted?",
  "What did I correct most this week — and was it shaping the qualities I said I wanted?",
  "Apa yang paling sering kita tegur minggu ini — dan apakah itu membentuk kualitas yang kita inginkan?",
  "Apa yang paling sering saya tegur minggu ini — dan apakah itu membentuk kualitas yang saya inginkan?"),
 (2,"Formation, Not Control","Pembentukan, Bukan Pengendalian",
  "Effective parenting is formation, not control.",
  "Mengasuh secara efektif adalah pembentukan, bukan pengendalian.",
  "Where am I parenting from fear of how my child looks? Where from vision of who they're becoming?",
  "Di mana saya mengasuh dari rasa takut akan penampilan anak? Di mana dari visi tentang siapa mereka kelak?",
  "When this week did we parent from fear, and when from vision?",
  "When this week did I parent from fear, and when from vision?",
  "Kapan minggu ini kita mengasuh dari rasa takut, dan kapan dari visi?",
  "Kapan minggu ini saya mengasuh dari rasa takut, dan kapan dari visi?"),
 (3,"One Rule, Reframed","Satu Aturan, Dimaknai Ulang",
  "Reframe \"stop doing X\" into \"build Y.\"",
  "Ubah \"jangan lakukan X\" menjadi \"bangun Y.\"",
  "One rule I'll reframe this week from a stop-doing into a build-towards.",
  "Satu aturan yang akan saya ubah minggu ini — dari larangan menjadi pembangunan.",
  "Which reframe felt most natural to live this week — and which felt forced?",
  "Which reframe felt most natural to live this week — and which felt forced?",
  "Pemaknaan ulang mana yang terasa paling alami dijalani minggu ini — dan mana yang terasa dipaksakan?",
  "Pemaknaan ulang mana yang terasa paling alami dijalani minggu ini — dan mana yang terasa dipaksakan?"),
 (4,"What Actually Stuck","Apa yang Benar-Benar Bertahan",
  "Insight that doesn't get repeated isn't yet a change.",
  "Pemahaman yang tidak diulang belum menjadi perubahan.",
  "Which one shift from the last three weeks do I want to keep building?",
  "Dari tiga minggu terakhir, satu perubahan mana yang ingin saya teruskan?",
  "What's one belief about parenting we held a month ago that's already shifting?",
  "What's one belief about parenting I held a month ago that's already shifting?",
  "Satu keyakinan tentang pengasuhan yang kita pegang sebulan lalu — yang sekarang mulai berubah?",
  "Satu keyakinan tentang pengasuhan yang saya pegang sebulan lalu — yang sekarang mulai berubah?"),
 (5,"What Is Age-Typical Here","Apa yang Wajar di Usia Ini",
  "Most \"bad behavior\" is developmental, not moral.",
  "Sebagian besar \"perilaku buruk\" bersifat perkembangan, bukan moral.",
  "One behavior I find frustrating — what age-typical thing might be underneath it?",
  "Satu perilaku yang membuat saya frustrasi — hal apa yang wajar di usia anak yang mungkin ada di baliknya?",
  "What did our child do this week that we called naughty, but was actually young?",
  "What did my child do this week that I called naughty, but was actually young?",
  "Apa yang dilakukan anak kita minggu ini — yang awalnya kita sebut nakal, padahal hanya tanda usia muda?",
  "Apa yang dilakukan anak saya minggu ini — yang awalnya saya sebut nakal, padahal hanya tanda usia muda?"),
 (6,"Brains Under Construction","Otak yang Masih Dibangun",
  "A child's brain doesn't finish maturing until the mid-twenties.",
  "Otak anak baru matang di pertengahan usia 20-an.",
  "Where am I expecting adult skills from a child whose brain isn't built for it yet?",
  "Di mana saya menuntut keterampilan orang dewasa dari otak anak yang belum siap?",
  "Where did we ask too much of our child this week — and not see it until now?",
  "Where did I ask too much of my child this week — and not see it until now?",
  "Di mana kita meminta terlalu banyak dari anak minggu ini — dan baru menyadarinya sekarang?",
  "Di mana saya meminta terlalu banyak dari anak minggu ini — dan baru menyadarinya sekarang?"),
 (7,"Drop One Expectation","Turunkan Satu Ekspektasi",
  "Lowering one age-inappropriate expectation can shift a whole household.",
  "Menurunkan satu ekspektasi yang tidak sesuai usia bisa mengubah seluruh suasana rumah.",
  "One expectation I'll quietly drop this week — and see what happens.",
  "Satu ekspektasi yang akan saya lepaskan diam-diam minggu ini — dan lihat apa yang terjadi.",
  "What got easier this week when we stopped expecting something our child wasn't ready for?",
  "What got easier this week when I stopped expecting something my child wasn't ready for?",
  "Apa yang jadi lebih mudah minggu ini ketika kita berhenti menuntut sesuatu yang anak belum siap?",
  "Apa yang jadi lebih mudah minggu ini ketika saya berhenti menuntut sesuatu yang anak belum siap?"),
 (8,"Knowing My Child's Age","Mengenal Usia Anak Saya",
  "Patience is mostly knowledge — knowing what a child can and can't yet do.",
  "Kesabaran sebagian besar adalah pengetahuan — tahu apa yang bisa dan belum bisa dilakukan anak.",
  "What do I now understand about my child's age that I didn't a month ago?",
  "Apa yang sekarang saya pahami tentang usia anak saya, yang sebulan lalu belum saya pahami?",
  "How is our child different from our picture of them four weeks ago?",
  "How is my child different from my picture of them four weeks ago?",
  "Bagaimana anak kita berbeda dari gambaran kita tentang dia empat minggu lalu?",
  "Bagaimana anak saya berbeda dari gambaran saya tentang dia empat minggu lalu?"),
 (9,"What's in My Body","Apa yang Terjadi di Tubuh Saya",
  "The body teaches first; words come second.",
  "Tubuh mengajar lebih dulu; kata-kata datang setelahnya.",
  "Where do I feel my stress in my body? Jaw, shoulders, breath, stomach?",
  "Di mana saya merasakan stres di tubuh saya? Rahang, bahu, napas, perut?",
  "What was happening in our bodies just before each hard moment this week?",
  "What was happening in my body just before each hard moment this week?",
  "Apa yang terjadi di tubuh kita tepat sebelum setiap momen sulit minggu ini?",
  "Apa yang terjadi di tubuh saya tepat sebelum setiap momen sulit minggu ini?"),
 (10,"My Top Triggers","Pemicu Utama Saya",
  "Triggers are old wounds asking for attention, not enemies.",
  "Pemicu adalah luka lama yang minta perhatian, bukan musuh.",
  "Three things that reliably set me off this week.",
  "Tiga hal yang hampir selalu memicu saya minggu ini.",
  "What's a trigger we share — and a trigger only one of us has?",
  "What's a trigger I'm carrying that I didn't put there myself?",
  "Pemicu apa yang sama-sama kita miliki — dan pemicu apa yang hanya dimiliki salah satu dari kita?",
  "Pemicu apa yang saya bawa, padahal bukan saya yang menaruhnya di sana?"),
 (11,"The Three-Breath Pause","Jeda Tiga Tarikan Napas",
  "Three breaths is enough time to choose between reactive and wise.",
  "Tiga tarikan napas cukup untuk memilih antara reaktif dan bijak.",
  "Where in my day will I deliberately practice three breaths before responding?",
  "Di bagian hari mana saya akan sengaja berlatih tiga tarikan napas sebelum merespons?",
  "When did one of us pause this week — and what changed because of it?",
  "When did I pause this week — and what changed because of it?",
  "Kapan salah satu dari kita berhenti sejenak minggu ini — dan apa yang berubah karenanya?",
  "Kapan saya berhenti sejenak minggu ini — dan apa yang berubah karenanya?"),
 (12,"My Anchor Practice","Kebiasaan Penenang Saya",
  "Self-regulation is daily, not occasional.",
  "Regulasi diri itu harian, bukan sesekali.",
  "One small daily practice that helps my nervous system reset.",
  "Satu kebiasaan kecil harian yang membantu sistem saraf saya tenang.",
  "What does each of us most need in order to stay steady this season?",
  "What do I most need to stay steady this season — and who can help me get it?",
  "Apa yang paling dibutuhkan masing-masing dari kita untuk tetap stabil musim ini?",
  "Apa yang paling saya butuhkan untuk tetap stabil musim ini — dan siapa yang bisa membantu?"),
 (13,"Listening or Waiting to Speak","Mendengar atau Menunggu Giliran Bicara",
  "Most adults listen for their turn, not for what's being said.",
  "Sebagian besar orang dewasa mendengar untuk menunggu giliran, bukan untuk memahami.",
  "When I'm with my child this week, am I listening or waiting to speak?",
  "Saat bersama anak minggu ini, apakah saya mendengarkan atau menunggu giliran bicara?",
  "Who in our family felt most heard this week — and who least?",
  "Who in our family felt most heard this week — and who least?",
  "Siapa di keluarga kita yang paling merasa didengar minggu ini — dan siapa yang paling tidak?",
  "Siapa di keluarga kita yang paling merasa didengar minggu ini — dan siapa yang paling tidak?"),
 (14,"Empathy First","Empati Dulu",
  "A child whose feelings are named settles faster than one who is corrected.",
  "Anak yang perasaannya dinamai akan tenang lebih cepat daripada yang langsung ditegur.",
  "What would change if I named my child's feeling before I corrected the behavior?",
  "Apa yang akan berubah jika saya menamai perasaan anak sebelum menegur perilakunya?",
  "When did empathy shorten a hard moment this week instead of lengthening it?",
  "When did empathy shorten a hard moment this week instead of lengthening it?",
  "Kapan empati memperpendek momen sulit minggu ini — alih-alih memperpanjangnya?",
  "Kapan empati memperpendek momen sulit minggu ini — alih-alih memperpanjangnya?"),
 (15,"Tell Me More","Cerita Lagi Dong",
  "\"Tell me more\" is more powerful than any explanation I can offer.",
  "\"Cerita lagi dong\" lebih kuat daripada penjelasan apa pun yang bisa saya tawarkan.",
  "I'll try \"tell me more\" three times before I try \"let me explain\" once.",
  "Saya akan mencoba \"cerita lagi dong\" tiga kali sebelum \"sini Mama/Papa jelaskan\" satu kali.",
  "What did we learn about our child this week by listening longer?",
  "What did I learn about my child this week by listening longer?",
  "Apa yang kita pelajari tentang anak kita minggu ini dengan mendengarkan lebih lama?",
  "Apa yang saya pelajari tentang anak saya minggu ini dengan mendengarkan lebih lama?"),
 (16,"How We Sound at Home","Suasana Suara di Rumah",
  "Children remember tone longer than they remember words.",
  "Anak mengingat nada suara lebih lama daripada kata-kata.",
  "What is the dominant tone in our home this season — and is it the one I want?",
  "Nada apa yang paling dominan di rumah kami musim ini — dan apakah itu nada yang saya inginkan?",
  "If our child described how we talk to each other, what would they say?",
  "If my child described how I talk to them, what would they say?",
  "Kalau anak kita menggambarkan cara kita berbicara satu sama lain, apa yang akan dia katakan?",
  "Kalau anak saya menggambarkan cara saya berbicara dengannya, apa yang akan dia katakan?"),
 (17,"What I Actually Do","Apa yang Sebenarnya Saya Lakukan",
  "Most discipline happens reactively, not by design.",
  "Sebagian besar disiplin terjadi secara reaktif, bukan terencana.",
  "Honestly — what does my discipline look like when I'm tired?",
  "Jujur — disiplin saya seperti apa ketika saya lelah?",
  "Where this week did our discipline come from a plan, and where from frustration?",
  "Where this week did my discipline come from a plan, and where from frustration?",
  "Di mana disiplin kita minggu ini datang dari rencana, dan di mana dari frustrasi?",
  "Di mana disiplin saya minggu ini datang dari rencana, dan di mana dari frustrasi?"),
 (18,"Firm and Warm","Tegas dan Hangat",
  "\"I see you're upset, AND we still need to leave.\" Both, in one sentence.",
  "\"Mama tahu kamu kesal, DAN kita tetap perlu pergi.\" Keduanya, dalam satu kalimat.",
  "Where do I drop firmness when I get warm — or warmth when I get firm?",
  "Di mana saya melepas ketegasan ketika hangat — atau kehangatan ketika tegas?",
  "When did one of us hold firm and warm at once this week — and what made it possible?",
  "When did I hold firm and warm at once this week — and what made it possible?",
  "Kapan salah satu dari kita memegang tegas dan hangat sekaligus minggu ini — dan apa yang membuatnya mungkin?",
  "Kapan saya memegang tegas dan hangat sekaligus minggu ini — dan apa yang membuatnya mungkin?"),
 (19,"Pre-Decided Response","Respons yang Sudah Ditentukan",
  "Consistency, not intensity, is what changes a child's nervous system.",
  "Yang mengubah sistem saraf anak adalah konsistensi, bukan intensitas.",
  "One recurring behavior — my pre-decided calm response, written before it happens.",
  "Satu perilaku berulang — respons tenang saya yang sudah ditetapkan sebelum kejadian.",
  "How did pre-deciding a response change the temperature of the moment this week?",
  "How did pre-deciding a response change the temperature of the moment this week?",
  "Bagaimana respons yang sudah direncanakan mengubah suhu momen minggu ini?",
  "Bagaimana respons yang sudah direncanakan mengubah suhu momen minggu ini?"),
 (20,"Repair Is Part of Discipline","Memperbaiki Adalah Bagian dari Disiplin",
  "Repair after rupture builds more security than a perfect day ever could.",
  "Memperbaiki setelah keretakan membangun rasa aman lebih dalam daripada hari yang sempurna.",
  "If I lost my calm this month, did I repair? What does repair actually sound like?",
  "Jika saya kehilangan kendali bulan ini, apakah saya memperbaikinya? Seperti apa bunyinya?",
  "What's a rupture from this month that one of us still needs to repair?",
  "What's a rupture from this month that I still need to repair?",
  "Keretakan apa dari bulan ini yang masih perlu diperbaiki salah satu dari kita?",
  "Keretakan apa dari bulan ini yang masih perlu saya perbaiki?"),
 (21,"The Vocabulary We Use","Kosakata yang Kita Gunakan",
  "Emotion vocabulary is itself a regulation tool.",
  "Kosakata emosi itu sendiri adalah alat regulasi.",
  "What feeling words does my child actually have access to right now?",
  "Kata-kata perasaan apa yang sebenarnya bisa diakses anak saya sekarang?",
  "What new feeling word did our child use this week — and what story was underneath it?",
  "What new feeling word did my child use this week — and what story was underneath it?",
  "Kata perasaan baru apa yang dipakai anak kita minggu ini — dan cerita apa di baliknya?",
  "Kata perasaan baru apa yang dipakai anak saya minggu ini — dan cerita apa di baliknya?"),
 (22,"Sit With It First","Temani Dulu",
  "All feelings are okay. Not all behaviors are.",
  "Semua perasaan boleh. Tidak semua perilaku boleh.",
  "Which of my child's feelings am I quickest to fix instead of sit with?",
  "Perasaan anak yang mana yang paling cepat saya perbaiki — bukan saya temani?",
  "Which feeling did our child have this week that we let them have, instead of solving?",
  "Which feeling did my child have this week that I let them have, instead of solving?",
  "Perasaan apa yang anak kita alami minggu ini yang kita biarkan dia rasakan — bukan langsung diselesaikan?",
  "Perasaan apa yang anak saya alami minggu ini yang saya biarkan dia rasakan — bukan langsung diselesaikan?"),
 (23,"Naming Without Fixing","Menamai Tanpa Memperbaiki",
  "\"It looks like you're feeling left out\" is enough. The fix can wait.",
  "\"Sepertinya kamu merasa tersisih\" itu sudah cukup. Solusinya bisa menunggu.",
  "I'll name a feeling once a day and not follow it with advice.",
  "Saya akan menamai satu perasaan setiap hari dan tidak menyusulinya dengan nasihat.",
  "When did naming a feeling — without fixing it — actually change the moment this week?",
  "When did naming a feeling — without fixing it — actually change the moment this week?",
  "Kapan menamai perasaan — tanpa memperbaikinya — benar-benar mengubah momen minggu ini?",
  "Kapan menamai perasaan — tanpa memperbaikinya — benar-benar mengubah momen minggu ini?"),
 (24,"What Was I Allowed to Feel","Perasaan yang Dulu Boleh Saya Rasakan",
  "We give what we were given. Or we choose to give what we weren't.",
  "Kita memberi apa yang dulu diberikan kepada kita. Atau memilih memberi apa yang dulu tidak kita dapatkan.",
  "Which feelings was I not allowed to have growing up? Am I allowing them in my child?",
  "Perasaan apa yang dulu tidak boleh saya rasakan? Apakah saya mengizinkannya dalam diri anak?",
  "What feeling do we as parents still struggle to feel ourselves — let alone make room for?",
  "What feeling do I still struggle to feel myself — let alone make room for in my child?",
  "Perasaan apa yang sebagai orang tua masih sulit kita rasakan sendiri — apalagi memberi ruang untuknya?",
  "Perasaan apa yang masih sulit saya rasakan sendiri — apalagi memberi ruang untuknya dalam diri anak?"),
 (25,"Where the Friction Lives","Di Mana Gesekan Hidup",
  "Most family friction lives at predictable transitions, not in character.",
  "Sebagian besar gesekan keluarga muncul di transisi yang bisa diprediksi, bukan di karakter.",
  "Which transition is hardest in our home this week? Morning? Bedtime? Meals? Screens?",
  "Transisi mana yang paling sulit di rumah kami minggu ini? Pagi? Tidur? Makan? Layar?",
  "Where did the same fight happen at the same time this week — and what does that tell us?",
  "Where did the same fight happen at the same time this week — and what does that tell me?",
  "Di mana pertengkaran yang sama terjadi di waktu yang sama minggu ini — dan apa artinya?",
  "Di mana pertengkaran yang sama terjadi di waktu yang sama minggu ini — dan apa artinya?"),
 (26,"Systems Beat Reminders","Sistem Mengalahkan Peringatan",
  "A well-designed routine reduces conflict for everyone.",
  "Rutinitas yang dirancang baik mengurangi konflik bagi semua.",
  "What am I solving by reminding — that a system could solve once?",
  "Apa yang saya selesaikan dengan terus menegur — yang sebenarnya bisa diselesaikan sistem?",
  "What's one thing we're each tired of reminding about — that we could redesign instead?",
  "What's one thing I'm tired of reminding about — that I could redesign instead?",
  "Satu hal yang kita berdua lelah menegurnya — yang bisa kita rancang ulang?",
  "Satu hal yang saya lelah menegurnya — yang bisa saya rancang ulang?"),
 (27,"One Routine, Redesigned","Satu Rutinitas, Dirancang Ulang",
  "Test a redesign for one week before judging it.",
  "Uji rancangan baru selama satu minggu sebelum menilai.",
  "Pick one routine. Make it shorter, clearer, more visual. Test it for seven days.",
  "Pilih satu rutinitas. Buat lebih singkat, jelas, visual. Uji selama tujuh hari.",
  "Did the redesign actually work this week — or did we just hope it would?",
  "Did the redesign actually work this week — or did I just hope it would?",
  "Apakah rancangan baru benar-benar berhasil minggu ini — atau kita hanya berharap?",
  "Apakah rancangan baru benar-benar berhasil minggu ini — atau saya hanya berharap?"),
 (28,"What Our Home Feels Like","Bagaimana Rasanya Rumah Kami",
  "A home is the sum of its repeated daily moments.",
  "Rumah adalah jumlah dari momen harian yang terulang.",
  "If I walked into our home as a stranger today, what would the rhythm feel like?",
  "Jika saya masuk ke rumah kami sebagai orang asing hari ini, ritme seperti apa yang saya rasakan?",
  "What does our home feel like this season — and is it close to what we want?",
  "What does our home feel like this season — and is it close to what I want?",
  "Bagaimana rasanya rumah kami musim ini — dan apakah dekat dengan yang kita inginkan?",
  "Bagaimana rasanya rumah kami musim ini — dan apakah dekat dengan yang saya inginkan?"),
 (29,"What Keeps Repeating","Apa yang Terus Berulang",
  "Repeating behavior has a function. Find the function first.",
  "Perilaku berulang memiliki fungsi. Temukan fungsinya dulu.",
  "What behavior is on repeat right now — and what might it be trying to communicate?",
  "Perilaku apa yang berulang sekarang — dan apa yang mungkin sedang dikomunikasikan?",
  "What behavior keeps showing up that we've been trying to suppress instead of understand?",
  "What behavior keeps showing up that I've been trying to suppress instead of understand?",
  "Perilaku apa yang terus muncul yang coba kita tekan — bukan kita pahami?",
  "Perilaku apa yang terus muncul yang coba saya tekan — bukan saya pahami?"),
 (30,"Underneath the Behavior","Di Balik Perilaku Itu",
  "Hitting is a frustration problem. Lying is often safety. Whining is often connection.",
  "Memukul soal frustrasi. Berbohong sering soal rasa aman. Merengek sering soal kedekatan.",
  "If I had to name one unmet need underneath my child's hardest behavior — what would it be?",
  "Kalau harus menyebut satu kebutuhan tak terpenuhi di balik perilaku terberat anak — apa itu?",
  "What unmet need did we finally see clearly this week, after weeks of missing it?",
  "What unmet need did I finally see clearly this week, after weeks of missing it?",
  "Kebutuhan tak terpenuhi apa yang akhirnya kita lihat jelas minggu ini, setelah berminggu terlewat?",
  "Kebutuhan tak terpenuhi apa yang akhirnya saya lihat jelas minggu ini, setelah berminggu terlewat?"),
 (31,"Meet the Need First","Penuhi Kebutuhannya Dulu",
  "Address the need before adding the consequence.",
  "Tangani kebutuhannya sebelum menambah konsekuensi.",
  "One need-meeting strategy I'll try this week before I add another consequence.",
  "Satu strategi pemenuhan kebutuhan yang akan saya coba minggu ini sebelum menambah konsekuensi.",
  "What softened this week when we addressed a need instead of a behavior?",
  "What softened this week when I addressed a need instead of a behavior?",
  "Apa yang melembut minggu ini ketika kita menangani kebutuhan, bukan perilaku?",
  "Apa yang melembut minggu ini ketika saya menangani kebutuhan, bukan perilaku?"),
 (32,"What's Hard Is Information","Yang Sulit Adalah Informasi",
  "A struggling child is communicating, not misbehaving.",
  "Anak yang kesulitan sedang berkomunikasi, bukan berbuat nakal.",
  "What is the hardest behavior in our home telling us we've missed?",
  "Perilaku tersulit di rumah kami sedang memberi tahu kami apa yang terlewat?",
  "What does our hardest child need from us this season that we haven't given yet?",
  "What does my hardest child need from me this season that I haven't given yet?",
  "Apa yang dibutuhkan anak tersulit kita dari kita musim ini yang belum kita berikan?",
  "Apa yang dibutuhkan anak tersulit saya dari saya musim ini yang belum saya berikan?"),
 (33,"What I'm Doing For Them","Apa yang Saya Lakukan Untuk Mereka",
  "Rescuing a child from healthy struggle stops their growth.",
  "Menyelamatkan anak dari perjuangan sehat menghentikan pertumbuhannya.",
  "What am I currently doing for my child that they could be doing for themselves?",
  "Apa yang saya lakukan untuk anak saya sekarang yang sebenarnya bisa dia lakukan sendiri?",
  "Where did we rescue too quickly this week — and where did we wisely let them struggle?",
  "Where did I rescue too quickly this week — and where did I wisely let them struggle?",
  "Di mana kita terlalu cepat menyelamatkan minggu ini — dan di mana kita bijak membiarkannya berjuang?",
  "Di mana saya terlalu cepat menyelamatkan minggu ini — dan di mana saya bijak membiarkannya berjuang?"),
 (34,"Character Is Built Slowly","Karakter Dibangun Perlahan",
  "Character is built one small repeated act at a time.",
  "Karakter dibangun satu tindakan kecil yang berulang dalam satu waktu.",
  "What's one tiny daily responsibility that would build the character I most want?",
  "Tanggung jawab harian kecil apa yang akan membangun karakter yang paling saya inginkan?",
  "What did our child do this week — small but real — that we can name as character growth?",
  "What did my child do this week — small but real — that I can name as character growth?",
  "Apa yang dilakukan anak kita minggu ini — kecil tapi nyata — yang bisa kita sebut pertumbuhan karakter?",
  "Apa yang dilakukan anak saya minggu ini — kecil tapi nyata — yang bisa saya sebut pertumbuhan karakter?"),
 (35,"Praise the Doing, Not the Child","Apresiasi Tindakan, Bukan Anaknya",
  "\"You set the table\" lands deeper than \"You're so good.\"",
  "\"Kamu sudah menata mejanya\" masuk lebih dalam daripada \"Kamu anak baik.\"",
  "I'll praise an action three times this week without praising the child as a category.",
  "Saya akan mengapresiasi tindakan tiga kali minggu ini tanpa memuji anak sebagai kategori.",
  "How did our child receive specific praise this week — differently than general praise?",
  "How did my child receive specific praise this week — differently than general praise?",
  "Bagaimana anak kita menerima pujian spesifik minggu ini — berbeda dari pujian umum?",
  "Bagaimana anak saya menerima pujian spesifik minggu ini — berbeda dari pujian umum?"),
 (36,"Becoming, Not Performing","Bertumbuh, Bukan Tampil",
  "We are raising a person, not curating a behavior.",
  "Kita sedang membentuk seorang pribadi, bukan mengatur sebuah penampilan.",
  "Where am I confusing my child's performance with their character?",
  "Di mana saya keliru menyamakan penampilan anak dengan karakternya?",
  "What does our child do when no one is watching — and what does that tell us?",
  "What does my child do when no one is watching — and what does that tell me?",
  "Apa yang dilakukan anak kita saat tidak ada yang melihat — dan apa artinya?",
  "Apa yang dilakukan anak saya saat tidak ada yang melihat — dan apa artinya?"),
 (37,"Transactional or Relational","Transaksional atau Relasional",
  "Children can tell when you're managing them versus being with them.",
  "Anak bisa merasakan kapan Anda mengatur mereka, dan kapan Anda hadir bersama mereka.",
  "Honestly — am I in mostly transactional mode with my child right now? Or relational?",
  "Jujur — apakah saya sebagian besar dalam mode transaksional dengan anak sekarang? Atau relasional?",
  "When this week did our child feel like a relationship to us — versus a project?",
  "When this week did my child feel like a relationship to me — versus a project?",
  "Kapan minggu ini anak kita terasa seperti relasi bagi kita — bukan sebuah proyek?",
  "Kapan minggu ini anak saya terasa seperti relasi bagi saya — bukan sebuah proyek?"),
 (38,"The Relationship Is the Curriculum","Hubungan Adalah Kurikulumnya",
  "Connection is what makes everything else work.",
  "Kedekatan adalah yang membuat segala hal lain berfungsi.",
  "Without connection, my best parenting tool doesn't land. Where am I missing connection now?",
  "Tanpa kedekatan, alat terbaik pun tidak mendarat. Di mana kedekatan saya hilang sekarang?",
  "What in our family worked this week mostly because connection was strong underneath?",
  "What in our family worked this week mostly because connection was strong underneath?",
  "Apa di keluarga kita yang berjalan baik minggu ini terutama karena kedekatan kuat di bawahnya?",
  "Apa di keluarga saya yang berjalan baik minggu ini terutama karena kedekatan kuat di bawahnya?"),
 (39,"Ten Minutes, Daily","Sepuluh Menit, Setiap Hari",
  "Phone away. Child leads. No teaching, no fixing.",
  "HP disimpan. Anak yang memimpin. Tidak mengajari, tidak memperbaiki.",
  "Ten minutes daily this week. Where in my day will it actually fit?",
  "Sepuluh menit setiap hari minggu ini. Di mana di hari saya itu benar-benar bisa muat?",
  "What did we learn about our child this week from ten minutes a day with no agenda?",
  "What did I learn about my child this week from ten minutes a day with no agenda?",
  "Apa yang kita pelajari tentang anak kita minggu ini dari sepuluh menit sehari tanpa agenda?",
  "Apa yang saya pelajari tentang anak saya minggu ini dari sepuluh menit sehari tanpa agenda?"),
 (40,"Do They Feel Known","Apakah Mereka Merasa Dikenal",
  "A child who feels deeply known cooperates from love, not fear.",
  "Anak yang merasa benar-benar dikenal bekerja sama karena cinta, bukan takut.",
  "Does my child feel known by me — or just managed?",
  "Apakah anak saya merasa dikenal oleh saya — atau hanya diatur?",
  "What's one thing each of us knows about our child that the other might not?",
  "What's one thing I know about my child that almost no one else does?",
  "Satu hal yang masing-masing dari kita tahu tentang anak kita, yang mungkin tidak diketahui pasangan?",
  "Satu hal yang saya tahu tentang anak saya, yang hampir tidak ada orang lain yang tahu?"),
 (41,"What Season Is This","Musim Apa Ini",
  "Pressure outside the family always shows up inside the family.",
  "Tekanan di luar keluarga selalu muncul di dalam keluarga.",
  "What season is our family actually in right now? Not what I wish — what it is.",
  "Musim apa yang sebenarnya sedang dialami keluarga kami sekarang? Bukan yang saya harapkan — yang sesungguhnya.",
  "What pressure are we both carrying this season that's leaking into our parenting?",
  "What pressure am I carrying this season that's leaking into my parenting?",
  "Tekanan apa yang kita berdua bawa musim ini yang merembet ke pengasuhan kita?",
  "Tekanan apa yang saya bawa musim ini yang merembet ke pengasuhan saya?"),
 (42,"Hard Month, Not Hard Child","Bulan yang Berat, Bukan Anak yang Berat",
  "Children absorb pressure that doesn't belong to them, unless we name it.",
  "Anak menyerap tekanan yang bukan miliknya, kecuali kita menamainya.",
  "What pressure has my child been absorbing that's actually mine?",
  "Tekanan apa yang sedang diserap anak saya, yang sebenarnya milik saya?",
  "What did we ask our child to absorb this season that wasn't theirs to carry?",
  "What did I ask my child to absorb this season that wasn't theirs to carry?",
  "Apa yang kita minta anak kita tanggung musim ini, padahal bukan bebannya?",
  "Apa yang saya minta anak saya tanggung musim ini, padahal bukan bebannya?"),
 (43,"Lower One Expectation","Turunkan Satu Ekspektasi",
  "A wise parent matches their expectations to the actual season.",
  "Orang tua yang bijak menyesuaikan ekspektasi dengan musim yang sebenarnya.",
  "One expectation I'll lower this week to match the season we're actually in.",
  "Satu ekspektasi yang akan saya turunkan minggu ini agar sesuai musim yang sebenarnya kami alami.",
  "What got softer this week when we lowered an expectation that didn't fit the season?",
  "What got softer this week when I lowered an expectation that didn't fit the season?",
  "Apa yang jadi lebih lembut minggu ini ketika kita menurunkan ekspektasi yang tidak sesuai musim?",
  "Apa yang jadi lebih lembut minggu ini ketika saya menurunkan ekspektasi yang tidak sesuai musim?"),
 (44,"Where I Find Support","Di Mana Saya Menemukan Dukungan",
  "No parent does this alone. Pretending to is the failure mode.",
  "Tidak ada orang tua yang melakukan ini sendirian. Berpura-pura sebaliknya adalah kegagalannya.",
  "Who supports me as a parent right now? If the answer is no one — what would help?",
  "Siapa yang mendukung saya sebagai orang tua sekarang? Kalau jawabannya tidak ada — apa yang bisa membantu?",
  "Who could we lean on more this season — and what's stopping us?",
  "Who could I lean on more this season — and what's stopping me?",
  "Pada siapa kita bisa lebih bersandar musim ini — dan apa yang menahan kita?",
  "Pada siapa saya bisa lebih bersandar musim ini — dan apa yang menahan saya?"),
 (45,"What I've Actually Changed","Apa yang Sudah Saya Ubah",
  "Real change is small, daily, and easy to miss.",
  "Perubahan nyata itu kecil, harian, dan mudah terlewat.",
  "What's one thing I do as a parent now that I didn't ten months ago?",
  "Satu hal yang saya lakukan sebagai orang tua sekarang, yang tidak saya lakukan sepuluh bulan lalu?",
  "Looking back at the year — what's a small, real change in how we parent now?",
  "Looking back at the year — what's a small, real change in how I parent now?",
  "Melihat ke belakang sepanjang tahun ini — perubahan kecil yang nyata apa di cara kita mengasuh sekarang?",
  "Melihat ke belakang sepanjang tahun ini — perubahan kecil yang nyata apa di cara saya mengasuh sekarang?"),
 (46,"What Compounded","Apa yang Berlipat Ganda",
  "Daily small effort always beats occasional heroic effort.",
  "Usaha kecil yang harian selalu mengalahkan usaha heroik yang sesekali.",
  "What practice from this year has compounded into something real?",
  "Praktik apa dari tahun ini yang sudah berlipat ganda menjadi sesuatu yang nyata?",
  "What habit grew so quietly this year that we almost didn't notice it taking root?",
  "What habit grew so quietly this year that I almost didn't notice it taking root?",
  "Kebiasaan apa yang tumbuh begitu tenang tahun ini, sampai kita hampir tidak menyadarinya berakar?",
  "Kebiasaan apa yang tumbuh begitu tenang tahun ini, sampai saya hampir tidak menyadarinya berakar?"),
 (47,"One Practice to Carry Forward","Satu Praktik untuk Dibawa Maju",
  "You can't carry everything forward. Pick one.",
  "Tidak semua bisa dibawa maju. Pilih satu.",
  "If I could only keep one practice from this year — which one?",
  "Kalau saya hanya boleh mempertahankan satu praktik dari tahun ini — yang mana?",
  "If we could only keep three practices from this year, which three would they be?",
  "If I could only keep three practices from this year, which three would they be?",
  "Kalau kita hanya boleh mempertahankan tiga praktik dari tahun ini, tiga apa itu?",
  "Kalau saya hanya boleh mempertahankan tiga praktik dari tahun ini, tiga apa itu?"),
 (48,"Who I'm Becoming","Sedang Menjadi Siapa Saya",
  "Parenting forms us as much as it forms our children.",
  "Pengasuhan membentuk kita, sama seperti membentuk anak kita.",
  "Who am I becoming as a parent — and is it the person I want to be?",
  "Sedang menjadi siapa saya sebagai orang tua — dan apakah itu sosok yang saya inginkan?",
  "Who is each of us becoming as a parent — and what do we love about it?",
  "Who am I becoming as a parent — and what do I love about it?",
  "Sedang menjadi siapa masing-masing dari kita sebagai orang tua — dan apa yang kita sukai darinya?",
  "Sedang menjadi siapa saya sebagai orang tua — dan apa yang saya sukai darinya?"),
 (49,"What This Year Held","Apa yang Tahun Ini Berikan",
  "Memory shapes meaning. We remember what we name.",
  "Ingatan membentuk makna. Kita mengingat apa yang kita namai.",
  "What three moments from this year do I want to make sure I never forget?",
  "Tiga momen dari tahun ini yang ingin saya pastikan tidak akan pernah saya lupakan?",
  "What three moments from this year do we both want to remember always?",
  "What three moments from this year do I want to remember always?",
  "Tiga momen dari tahun ini yang kita berdua ingin selalu kenang?",
  "Tiga momen dari tahun ini yang ingin saya selalu kenang?"),
 (50,"What This Year Cost","Apa yang Tahun Ini Renggut",
  "Honest grief and honest gratitude both belong here.",
  "Duka yang jujur dan syukur yang jujur sama-sama berhak ada di sini.",
  "What was hard this year that I haven't yet let myself name?",
  "Apa yang sulit tahun ini, yang belum saya izinkan diri saya untuk menamainya?",
  "What did this year cost us — and was it worth it?",
  "What did this year cost me — and was it worth it?",
  "Apa yang harus kita bayar tahun ini — dan apakah itu sepadan?",
  "Apa yang harus saya bayar tahun ini — dan apakah itu sepadan?"),
 (51,"What I'm Letting Go Of","Apa yang Saya Lepaskan",
  "Growth requires releasing as much as adding.",
  "Pertumbuhan menuntut melepaskan, sama seperti menambah.",
  "What old story about myself as a parent am I ready to leave behind?",
  "Cerita lama tentang diri saya sebagai orang tua yang siap saya tinggalkan?",
  "What's one belief about parenting we're both ready to leave behind for next year?",
  "What's one belief about parenting I'm ready to leave behind for next year?",
  "Satu keyakinan tentang pengasuhan yang kita berdua siap tinggalkan untuk tahun depan?",
  "Satu keyakinan tentang pengasuhan yang saya siap tinggalkan untuk tahun depan?"),
 (52,"What Comes Next","Apa yang Datang Berikutnya",
  "A year of small steady work has changed something. Name it. Carry it forward.",
  "Setahun kerja kecil yang stabil sudah mengubah sesuatu. Namai. Bawa maju.",
  "What do I want to carry into next year — and what do I want to start fresh?",
  "Apa yang ingin saya bawa ke tahun depan — dan apa yang ingin saya mulai dari awal?",
  "What do we want our family to look like one year from today?",
  "What do I want our family to look like one year from today?",
  "Akan seperti apa kita ingin keluarga kita satu tahun dari hari ini?",
  "Akan seperti apa saya ingin keluarga kita satu tahun dari hari ini?"),
]

CHAPTER_NAMES = {
 1:("Parenting Mindset","Pola Pikir Pengasuhan"),
 2:("Child Development","Perkembangan Anak"),
 3:("Parent Self-Regulation","Regulasi Diri Orang Tua"),
 4:("Communication","Komunikasi"),
 5:("Discipline","Disiplin"),
 6:("Emotional Coaching","Pendampingan Emosi"),
 7:("Routines & Home Systems","Rutinitas & Sistem Rumah"),
 8:("Behavior Challenges","Tantangan Perilaku"),
 9:("Character & Responsibility","Karakter & Tanggung Jawab"),
 10:("Relationship & Attachment","Hubungan & Kelekatan"),
 11:("Special Contexts","Konteks Khusus"),
 12:("Integration & Year-End","Integrasi & Akhir Tahun"),
}

DAILY_PROMPTS = [
 {"en":"One moment with my child today","id":"Satu momen bersama anak hari ini"},
 {"en":"One feeling I noticed in myself","id":"Satu perasaan yang saya sadari dalam diri saya"},
 {"en":"One thing I want to try tomorrow","id":"Satu hal yang ingin saya coba besok"},
]

def week_to_chapter(n):
    # weeks 1-4 -> ch1, 5-8 -> ch2, ... 45-48 -> ch12; 49-52 also ch12 (year-end)
    return min(12, math.ceil(n/4))

out = {
 "meta":{
   "product":"diary",
   "freeThroughChapter":4,
   "dailyPrompts":DAILY_PROMPTS,
   "debrief":{
     "combined":[
       {"en":"One thing that worked this week","id":"Satu hal yang berhasil minggu ini"},
       {"en":"One thing that didn't","id":"Satu hal yang tidak berhasil"},
       {"en":"One agreement for next week","id":"Satu kesepakatan untuk minggu depan"},
     ],
     "solo":[
       {"en":"One thing that worked this week","id":"Satu hal yang berhasil minggu ini"},
       {"en":"One thing that didn't","id":"Satu hal yang tidak berhasil"},
       {"en":"One intention for next week","id":"Satu niat untuk minggu depan"},
     ],
   },
 },
 "chapters":[{"number":k,"en":v[0],"id":v[1]} for k,v in CHAPTER_NAMES.items()],
 "weeks":[],
}

for w in WEEKS:
    (n,ten,tid,pen,pid,ien,iid,sen,ssoloen,sid,ssoloid)=w
    ch=week_to_chapter(n)
    out["weeks"].append({
      "week":n,
      "chapter":ch,
      "locked": ch>4,
      "theme":{"en":ten,"id":tid},
      "principle":{"en":pen,"id":pid},
      "weekIntent":{"en":ien,"id":iid},
      "sundayReflection":{
        "combined":{"en":sen,"id":sid},
        "solo":{"en":ssoloen,"id":ssoloid},
      },
    })

with open("/home/claude/ceria_app/content/diary_weeks.json","w",encoding="utf-8") as f:
    json.dump(out,f,ensure_ascii=False,indent=2)

print(f"Wrote {len(out['weeks'])} weeks. Free weeks: {sum(1 for w in out['weeks'] if not w['locked'])}")
